[package]
name = "gif-out-loud"
version = "0.1.0"
authors = ["Alessandro Re <alessandro@standard.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.26.0"
gif = "0.10.3"
